name: Build, Test and Release
# This workflow will build, test and release our CLI

# we only run this workflow on the main (release) branch for both commits and PRs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # we start with the build job
  Build:
    runs-on: ubuntu-latest
    name: Build

    strategy:
      matrix:
        # building on nodejs LTS
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: building on Node.js ${{ matrix.node-version }} ğŸ› ï¸
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
        env:
            CI: true
  Test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        # building on nodejs LTS
        node-version: [14.x]
    steps:
     - uses: actions/checkout@v2
     - name: Running Tests ğŸ§ª
       uses: actions/setup-node@v1
       with:
          node-version: ${{ matrix.node-version }}
     - run: yarn
     - run: yarn test
  # we release if everything is fine
  Release:
    runs-on: ubuntu-latest
    name: Release
    needs: Test
    if: github.event_name == 'push'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing a release ğŸš€
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}